include ./libtests.mk
include ./config.mk

# Location of directories.
TMPDIR=tmp
BINDIR=bin

MYPHOTOSLIBPATH = $(LIBS_PHOTOS_PATH)
MYPHOTOSLIBNAME = libphotos.so
ifeq ($(TESTS_ARCHIVE),1)
 MYPHOTOSLIBPATH = $(LIBS_PHOTOS_PATH)/archive
 MYPHOTOSLIBNAME = libphotos.a
endif


install: $(MYPHOTOSLIBPATH)/$(MYPHOTOSLIBNAME)
$(MYPHOTOSLIBPATH)/$(MYPHOTOSLIBNAME) :
	cd $(MCGTESTDIR) && \
	cp $(MCGENERATORS)/distribution/photos/photos-$(PHOTOS_VERSION)-src.tgz . && \
	tar xfz photos-$(PHOTOS_VERSION)-src.tgz && \
	cd photos/$(PHOTOS_VERSION) && \
	./configure --lcgplatform=${PLATFORM} --userfflags=-fno-automatic --enable-shared && \
	make && \
	mkdir -p $(PHOTOS_PATH) && \
	cp -rf include lib $(PHOTOS_PATH)/

photos_test1: $(MYPHOTOSLIBPATH)/$(MYPHOTOSLIBNAME)
	@mkdir -p $(BINDIR)
	@mkdir -p $(TMPDIR)
	$(FC) $(FFLAGS) $(INCLUDE_PHOTOS) $(INCLUDE_PYTHIA6) $@.F -c -o $(TMPDIR)/$@.o
	$(CXX) $(CXXFLAGS) $(TMPDIR)/$@.o -o $(BINDIR)/$@.exe \
	-L$(LIBS_PYTHIA6_PATH) -lpythia6 \
	-L$(MYPHOTOSLIBPATH) -lphotos \
	-lpythia6_dummy -lpythia6_pdfdummy \
	-L$(LIBS_LIBTESTS_PATH)/archive -ltests \
	$(FLIBS)
	@ln -fs $(BINDIR)/$@.exe $@.exe
	@echo export LD_LIBRARY_PATH=$(LIBS_PYTHIA6_PATH):$(LIBS_PHOTOS_PATH):$(LD_LIBRARY_PATH) > ldlp.sh

# Clean up: remove executables and outdated files.
#.PHONY: clean distclean

clean:
	rm -f $(PROGNAME).exe ldlp.sh

distclean: clean
	rm -f $(BINDIR)/$(PROGNAME).exe
