#!/usr/bin/env bash

set -x
#------------------------------------------------------------------
svnrep=http://svn.cern.ch/guest/lcgsoft
svnrepcool=http://svn.cern.ch/guest/lcgcool/cool
svnrepcoral=http://svn.cern.ch/guest/lcgcoral/coral

rm -rf workdir
mkdir workdir
cd workdir
for tag in LCGCMT-cmake_root6 LCGCMT-cmake
do
  svn co $svnrep/tags/$tag/lcgcmt --quiet $tag
  tar --exclude=.svn -czf $tag.tar.gz $tag
  cp  $tag.tar.gz /afs/cern.ch/sw/lcg/external/tarFiles/.
done

for tag in COOL-preview COOL_3_0-preview
do
  svn co $svnrepcool/tags/$tag --quiet $tag
  if [[ $tag == "COOL_3_0-preview" ]]
  then
      tag_new="COOL-3_0-preview"
  else
      tag_new=$tag
  fi
  echo $tag_new
  tar --exclude=.svn -czf $tag_new.tar.gz $tag
  cp  $tag_new.tar.gz /afs/cern.ch/sw/lcg/external/tarFiles/.
done

for tag in CORAL-preview CORAL_3_0-preview
do
  svn co $svnrepcool/tags/$tag --quiet $tag
  if [[ $tag == "CORAL_3_0-preview" ]]
  then
      tag_new="CORAL-3_0-preview"
  else
      tag_new=$tag
  fi
  echo $tag_new
  tar --exclude=.svn -czf $tag_new.tar.gz $tag
  cp  $tag_new.tar.gz /afs/cern.ch/sw/lcg/external/tarFiles/.
done


