#!/usr/bin/env bash
#------------------------------------------------------------------
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

#---Compiler------------------------------------------------------
export CC=clang
export CXX=clang++
export FC=gfortran
export LIBRARY_PATH=/usr/local/gfortran/lib
export PATH=${PATH}:/usr/local/bin:/opt/X11/bin
export CXXFLAGS=-stdlib=libstdc++
#export LDFLAGS=-stdlib=libstdc++

#-----------------------------------------------------------------
THIS=$(dirname $0)

if [ x$MODE = x ]; then
  export MODE=Experimental
fi
if [ x$WORKDIR = x ]; then 
  WORKDIR=/ec/lcg-builds
fi
if [ x$VERSION = x ]; then
  export VERSION=trunk
fi
if [ x$TARGET = x ]; then
  export TARGET=all
fi

export BUILD_PREFIX=${WORKDIR}

#---Run the CTest script-------------------------------------------
echo "Starting CTest script for configuration ${CONFIG} at `date`" 

ctest -V -S ${THIS}/lcgcmake-build.cmake
