#!/usr/bin/env bash

#------------------------------------------------------------------
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

#---CMake----------------------------------------------------------
export PATH=/afs/cern.ch/sw/lcg/external/CMake/2.8.9/Linux-i386/bin:${PATH}

#---Compiler------------------------------------------------------
. /afs/cern.ch/sw/lcg/contrib/gcc/4.3.6/x86_64-slc5/setup.sh

#-----------------------------------------------------------------
THIS=$(dirname $0)

if [ x$MODE = x ]; then
  export MODE=experimental
fi
if [ x$WORKDIR = x ]; then 
  WORKDIR=/ec/lcg-builds
fi
if [ x$VERSION = x ]; then
  export VERSION=trunk
fi
if [ x$TARGET = x ]; then
  export TARGET=all
fi

CONFIG=slc5-gcc43

export SOURCE=${WORKDIR}/${MODE}/lcgcmake-${VERSION}
export BINARY=${WORKDIR}/${MODE}/${CONFIG}

#---Run the CTest script-------------------------------------------
echo "Starting CTest script for configutation ${CONFIG} at `date`" 

ctest -V -S ${THIS}/lcgcmake-build.cmake



