#!/usr/bin/env bash

#------------------------------------------------------------------
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

#---CMake----------------------------------------------------------
export PATH=/afs/cern.ch/sw/lcg/external/CMake/2.8.9/Linux-i386/bin:${PATH}

#---Compiler------------------------------------------------------
export PATH=/afs/cern.ch/sw/lcg/contrib/gcc/4.7.2/x86_64-slc5/bin:${PATH}
export LD_LIBRARY_PATH=/afs/cern.ch/sw/lcg/contrib/gcc/4.7.2/x86_64-slc5/lib64:${LD_LIBRARY_PATH}

#-----------------------------------------------------------------
THIS=$(dirname $0)

if [ x$MODE = x ]; then
  export MODE=experimental
fi
if [ x$WORKDIR = x ]; then 
  WORKDIR=/ec/build 
fi
if [ x$VERSION = x ]; then 
  export VERSION=g4tags-dev
fi
====>>


#---Enable FPE -----------------------------------------------------
export CXXFLAGS=-DG4FPE_DEBUG

if [ x$BUILDTYPE = xstaticlibs ]
then
  export G4_XOPTS="-DBUILD_STATIC_LIBS=ON;-DBUILD_SHARED_LIBS=OFF"
else
  export G4_XOPTS="-DGEANT4_USE_G3TOG4=ON;\
-DGEANT4_USE_OPENGL_X11=ON;\
-DGEANT4_USE_QT=ON;\
-DGEANT4_USE_RAYTRACER_X11=ON;\
-DGEANT4_USE_SYSTEM_CLHEP=ON;\
-DCLHEP_ROOT_DIR=${CLHEP_ROOT_DIR};\
-DGEANT4_USE_XM=ON"
fi

CONFIG=slc5-gcc47
export SOURCE=${WORKDIR}/${MODE}/${VERSION}
if [ x$BUILDTYPE = x ]; then
  export BINARY=${WORKDIR}/${MODE}/${CONFIG}
else
  export BINARY=${WORKDIR}/${MODE}/${CONFIG}-${BUILDTYPE}
fi

if [ ! -d "${SOURCE}" ]; then
  ${THIS}/g4tagsvn.py update -c ${VERSION} -d ${SOURCE} -q
fi

#---Run the CTest script-------------------------------------------
echo "Starting CTest script for configutation ${CONFIG} at `date`" 
ctest -V -S ${THIS}/g4${MODE}.cmake 



