#!/usr/bin/env bash

#------------------------------------------------------------------
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

#---CMake----------------------------------------------------------
export PATH=/afs/cern.ch/sw/lcg/contrib/CMake/2.8.12.2/Linux-i386/bin:$PATH

#---Compiler------------------------------------------------------
ARCH=$(uname -m)
. /afs/cern.ch/sw/lcg/contrib/gcc/4.7.2/${ARCH}-slc6/setup.sh
export CC=gcc
export CXX=g++
export FC=gfortran

#-----------------------------------------------------------------
THIS=$(dirname $0)

if [ x$MODE = x ]; then
  export MODE=Experimental
fi
if [ x$WORKDIR = x ]; then 
  WORKDIR=/ec/lcg-builds
fi
if [ x$VERSION = x ]; then 
  export VERSION=trunk
fi

export BUILD_PREFIX=${WORKDIR}

#if [ ! -d "${SOURCE}" ]; then
#  svn co svn+ssh://svn.cern.ch/reps/lcgsoft/trunk/lcgcmake ${SOURCE}
#fi

#---Run the CTest script-------------------------------------------
echo "Starting CTest script for configuration ${CONFIG} at `date`" 

ctest -V -S ${THIS}/lcgcmake-build.cmake



