#!/usr/bin/env bash

#------------------------------------------------------------------
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

#---CMake----------------------------------------------------------
export PATH=/afs/cern.ch/sw/lcg/external/CMake/2.8.9/Linux-i386/bin:${PATH}

#---GCC compiler to provide headers of standard libs---------------
ARCH=$(uname -m)
. /afs/cern.ch/sw/lcg/contrib/gcc/4.8.1/${ARCH}-slc6/setup.sh

#---Compiler-------------------------------------------------------
. /afs/cern.ch/sw/IntelSoftware/linux/setup.sh
. /afs/cern.ch/sw/IntelSoftware/linux/x86_64/xe2013/bin/ifortvars.sh intel64
. /afs/cern.ch/sw/IntelSoftware/linux/x86_64/xe2013/bin/iccvars.sh intel64
export CC=icc
export CXX=icc
export FC=ifort

#-----------------------------------------------------------------
THIS=$(dirname $0)

if [ x$MODE = x ]; then
  export MODE=Experimental
fi
if [ x$WORKDIR = x ]; then 
  WORKDIR=/ec/lcg-builds
fi
if [ x$VERSION = x ]; then
  export VERSION=trunk
fi
if [ x$TARGET = x ]; then
  export TARGET=all
fi

export BUILD_PREFIX=${WORKDIR}

#---Run the CTest script-------------------------------------------
echo "Starting CTest script for configuration ${CONFIG} at `date`" 

ctest -V -S ${THIS}/lcgcmake-build.cmake



