#!/bin/sh
#... making the check program:

cat > check.c << EOF
#include<stdio.h>
#include<math.h>
int main (void) {
double y,dy,y0,dy0,delta;
scanf ("%lE%lE%lE%lE",&y,&dy,&y0,&dy0);
delta = pow( pow(y-y0,2)/(dy*dy + dy0*dy0), 0.5);
printf(" deviation:%4.1lf sigma ", delta);
return delta < 4. ? 0 : 1;
}
EOF
cc -o check.exe check.c -lm

return_value=0 

cat test0tmp.dat | \
{
while read gename ntest y dy ; do 
   echo -n $gename test no. $ntest : 
   str=$(grep -E "$gename[ ]+$ntest " < test.dat) 
   if [ "x$str" != "x" ] ; then
      sedstr="s/${gename}[ ]\+${ntest} [ ]*//"      
      val=$(echo -n $str | sed "$sedstr")
      if [ "${val/ERROR/}" == "${val}" ] ; then
         echo $val $y $dy | ./check.exe
         ret=$?
         if [ "$ret" == "1" ] ; then 
            echo " : Deviation > 4 sigma ! "
            return_value=1
         else
            echo ""
         fi
      else
         echo " **** TEST FAILED ! ****"
         return_value=1
      fi
   else
      echo " **** ABSENT ! *****"
      return_value=1
   fi
done > ./result.txt
echo -ne "\n\n**** Test "
if [ "$return_value" == "1" ] ; then
    echo "failed ****" 
else
    echo "passed ****"
fi
echo -e "\n\n"
}

rm -f check.c check.exe

exit
