include ./libtests.mk
include ./config.mk

# Location of directories.

TMPDIR=tmp
BINDIR=bin

MYLIBSWINHAC=$(LIBS_WINHAC_PATH)
MYLIBSPYTHIA=$(LIBS_PYTHIA6_PATH)
MYLIBSLHAPDF=$(LIBS_LHAPDF_PATH)
MYPBLOCKDATA=
#MYPBLOCKDATA=$(LIBS_PYTHIA6_PATH)/pydata.o 
ifeq ($(TESTS_ARCHIVE),1)
 MYLIBSWINHAC = $(LIBS_WINHAC_PATH)/archive
 MYLIBSPYTHIA = $(LIBS_PYTHIA6_PATH)/archive
 MYLIBSLHAPDF = $(LIBS_LHAPDF_PATH)/archive
 MYPBLOCKDATA=  
endif

winhac_test: winhac.dat winhac_default.dat
	@mkdir -p $(TMPDIR)
	@mkdir -p $(BINDIR)
	$(FC) $(FFLAGS) $(INCLUDE_WINHAC) $@.F -c -o $(TMPDIR)/$@.o
	$(CXX) $(CXXFLAGS) $(TMPDIR)/$@.o $(MYPBLOCKDATA) -o $(BINDIR)/$@.exe \
	-L$(MYLIBSPYTHIA) -lpythia6  \
	-L$(MYLIBSWINHAC) -lwinhac -lfoam -lewcdec -lewcall \
	-L$(MYLIBSPYTHIA) -lpythia6 -lpythia6_dummy \
	-L$(MYLIBSLHAPDF) -lLHAPDF \
	$(FLIBS)
	@ln -fs $(BINDIR)/$@.exe $@.exe
	@rm -f ldlp.sh
	@echo "#!/bin/sh" > ldlp.sh
	@echo export LD_LIBRARY_PATH=$(LIBS_WINHAC_PATH):$(LIBS_PYTHIA6_PATH):$(LIBS_LHAPDF_PATH):$(LD_LIBRARY_PATH) >> ldlp.sh
	@echo export LHAPATH=$(LHAPDF_PATH)/../share/PDFsets >> ldlp.sh

winhac_default.dat:
	@ln -fs $(WINHAC_PATH)/../share/data/data_DEFAULTS ./$@

# Clean up: remove executables and outdated files.
.PHONY: clean distclean

clean:
	rm -f $(PROGNAME).exe ldlp.sh winhac_default.dat

distclean: clean
	rm -f $(BINDIR)/$(PROGNAME).exe winhac.output
	rm *~
