include ./libtests.mk
include ./config.mk

BINDIR=bin

vincia_test1: 
	@mkdir -p $(BINDIR)
	@ln -fs $(SHARE_VINCIA_PATH)/xmldoc
	@ln -fs $(SHARE_VINCIA_PATH)/antennae
	@ln -fs $(SHARE_VINCIA_PATH)/tunes
	$(CXX) $@.cc -o $(BINDIR)/$@.exe $(CXXFLAGS) \
	-I$(INCLUDE_LIBTESTS_PATH) -I$(INCLUDE_PYTHIA8_PATH) -I$(INCLUDE_VINCIA_PATH) \
	-L$(LIBS_PYTHIA8_PATH) -lpythia8 -llhapdfdummy \
	-L$(LIBS_VINCIA_PATH)/archive -lvincia -lmginterface -ldhelas3 \
	$(FLIBS)
	@ln -fs $(BINDIR)/$@.exe $@.exe
	@echo export LD_LIBRARY_PATH=$(LIBS_PYTHIA8_PATH):$(LD_LIBRARY_PATH) > ldlp.sh

# Clean up: remove executables and outdated files.
.PHONY: clean distclean vincia_test1

clean:
	rm -f $(PROGNAME).exe ldlp.sh  antennae tunes xmldoc

distclean: clean
	rm -f $(BINDIR)/$(PROGNAME).exe
