###################################################################################
# powheg-box r197 is tested
###################################################################################

include ./libtests.mk
include ./config.mk

# Location of directories.
TMPDIR=tmp
BINDIR=bin

MYPYTHIA8LIBPATH = $(PYTHIA8_PATH)/lib
MYPYTHIA8LIBNAME1 = libpythia8$(SOEXT)
MYPYTHIA8LIBNAME2 = libhepmcinterface$(SOEXT)
ifeq ($(TESTS_ARCHIVE),1)
 MYPYTHIA8LIBPATH = $(PYTHIA8_PATH)/lib/archive
 MYPYTHIA8LIBNAME1 = libpythia8.a
 MYPYTHIA8LIBNAME2 = libhepmcinterface.a
endif

MYPYTHIA6LIBPATH = $(LIBS_PYTHIA6_PATH)/archive
PYTHIA6LIBNAME = -lpythia6 -lpythia6_dummy -lpythia6_pdfdummy
MYTESTSLIBPATH = $(LIBS_LIBTESTS_PATH)/archive
HEPMCLOCATION = $(HEPMC_PATH)
CLHEPLOCATION = $(CLHEP_PATH)


MY_POWHEGBOX_EXE_NAME = Z

PROGNAME=powhegbox

powhegbox_bin: 
	@mkdir -p $(BINDIR)
	@mkdir -p powhegbox_bin
	@cp z-powheg.input ./powhegbox_bin
	@ln -fs ${POWHEGBOX_PATH}/../share/sources/pdfdata/cteq6m.tbl ./powhegbox_bin/cteq6m
	@ln -fs ${POWHEGBOX_PATH}/bin/$(MY_POWHEGBOX_EXE_NAME) ./powhegbox_bin/$(PROGNAME).exe
	@echo export LD_LIBRARY_PATH=$(MY_MCFM_LIB_PATH):$(LD_LIBRARY_PATH) > ldlp.sh

powhegbox_test1: $(MYPYTHIA8LIBPATH)/$(MYPYTHIA8LIBNAME1) $(MYPYTHIA8LIBPATH)/$(MYPYTHIA8LIBNAME2)
	 @mkdir -p $(BINDIR)
	 $(CXX) $(CXXFLAGS) \
	 $(INCLUDE_LIBTESTS) -I$(PYTHIA8_PATH)/include \
	 -I$(HEPMCLOCATION)/include -I$(CLHEPLOCATION)/include \
	 $@.cc -o $(BINDIR)/$@.exe \
	 -L$(MYPYTHIA8LIBPATH) -lpythia8 -lhepmcinterface -llhapdfdummy \
	 -L$(MYPYTHIA6LIBPATH) $(PYTHIA6LIBNAME) \
	 -L$(MYTESTSLIBPATH) -lanalyserhepmc \
	 -L$(HEPMCLOCATION)/lib -lHepMC \
	 -L$(CLHEPLOCATION)/lib -lCLHEP \
	 $(FLIBS)
	 @ln -fs $(BINDIR)/$@.exe $@.exe
	 @echo "export   LD_LIBRARY_PATH=$(MYPYTHIA8LIBPATH):$(HEPMCLOCATION)/lib:$(CLHEPLOCATION)/lib:$(LD_LIBRARY_PATH) ;"  > ldlp.sh
	 @echo "export DYLD_LIBRARY_PATH=$(MYPYTHIA8LIBPATH):$(HEPMCLOCATION)/lib:$(CLHEPLOCATION)/lib:$(LD_LIBRARY_PATH) ;" >> ldlp.sh

# Clean up: remove executables and outdated files.
.PHONY: clean distclean powhegbox_bin

clean:
	rm -f $(PROGNAME).exe ldlp.sh z-events.lhe

distclean: clean
	rm -f $(BINDIR)/$(PROGNAME).exe
