include ./libtests.mk
include ./config.mk

# Location of directories
TMPDIR=tmp
BINDIR=bin

MYLIBS=$(LIBS_TOPREX)
ifeq ($(TESTS_ARCHIVE),1)
  MYLIBS = $(LIBS_TOPREX_STATIC)
endif

toprex_test1:
	@mkdir -p $(BINDIR)
	$(FC) $(FFLAGS) $(INCLUDE_TOPREX) $@.F -c -o $(TMPDIR)/$@.o
	$(CXX) $(CXXFLAGS) $(TMPDIR)/$@.o -o $(BINDIR)/$@.exe \
	-L$(LIBS_PYTHIA6_PATH) -lpythia6 \
	$(MYLIBS) \
	-lpythia6_dummy -lpythia6_pdfdummy \
	-L(LIBS_LIBTESTS_PATH) -ltests -lcernlibgenser \
	$(FLIBS)
	@ln -fs $(BINDIR)/$@.exe $@.exe
	@echo export LD_LIBRARY_PATH=$(LIBS_PYTHIA6_PATH):$(LIBS_TOPREX_PATH):$(LIBS_LIBTESTS_PATH):$(LD_LIBRARY_PATH) > ldlp.sh

# Clean up: remove executables and outdated files.
.PHONY: clean distclean

clean:
	rm -f $(PROGNAME).exe ldlp.sh

distclean: clean
	rm -f $(BINDIR)/$(PROGNAME).exe
