include ./libtests.mk
include ./config.mk

# Location of directories.
TMPDIR=tmp
BINDIR=bin
MYLIBSCHARYB=$(LIBS_CHARYBDIS2_PATH)
MYLIBSPYTHIA=$(LIBS_PYTHIA6_PATH)
MYLIBSHERWIG=$(LIBS_HERWIG_PATH)

ifeq ($(TESTS_ARCHIVE),1)
 MYLIBSCHARYB = $(LIBS_CHARYBDIS2_PATH)/archive
 MYLIBSPYTHIA = $(LIBS_PYTHIA6_PATH)/archive
 MYLIBSHERWIG = $(LIBS_HERWIG_PATH)/archive
endif

charybdis2_test1:
	@mkdir -p $(BINDIR)
	@mkdir -p $(TMPDIR)
	@ln -fs /afs/cern.ch/sw/lcg/external/MCGenerators/charybdis2/1.0.3/share/data_files $(BINDIR)/data_files
	@ln -fs /afs/cern.ch/sw/lcg/external/MCGenerators/charybdis2/1.0.3/share/data_files data_files
	$(FC) $(FFLAGS) -I$(CHARYBDIS2_PATH)/include $@.F -c -o $(TMPDIR)/$@.o
	$(CXX) $(CXXFLAGS) $(TMPDIR)/$@.o -o $(BINDIR)/$@.exe \
	-L$(MYLIBSPYTHIA) -lpythia6 \
	-L$(MYLIBSCHARYB) -lcharybdis2-p \
	-L$(MYLIBSPYTHIA) -lpythia6_dummy -lpythia6_pdfdummy \
	$(FLIBS)
	@ln -fs $(BINDIR)/$@.exe $@.exe
	@echo export LD_LIBRARY_PATH=$(PYTHIA6_PATH)/lib:$(CHARYBDIS2_PATH)/lib:$(LD_LIBRARY_PATH) > ldlp.sh

charybdis2_test2:
	@mkdir -p $(BINDIR)
	@mkdir -p $(TMPDIR)
	@ln -fs /afs/cern.ch/sw/lcg/external/MCGenerators/charybdis2/1.0.3/share/data_files $(BINDIR)/data_files
	@ln -fs /afs/cern.ch/sw/lcg/external/MCGenerators/charybdis2/1.0.3/share/data_files data_files
	$(FC) $(FFLAGS) -I$(HERWIG_PATH)/include -I$(CHARYBDIS2_PATH)/include $@.F -c -o $(TMPDIR)/$@.o
	$(FC)  $(TMPDIR)/$@.o -o $(BINDIR)/$@.exe \
	-L$(MYLIBSPYTHIA) -lpythia6 \
	-L$(MYLIBSHERWIG) -lherwig \
	-L$(MYLIBSCHARYB) -lcharybdis2-h \
	-L$(MYLIBSHERWIG) -lherwig_dummy \
	-L$(MYLIBSPYTHIA) -lpythia6_dummy -lpythia6_pdfdummy \
	$(MYLIBSHERWIG)/hwudat.o \
	-L$(MYLIBSCHARYB) -lcharybdis2-h \
	-L$(MYLIBSHERWIG) -lherwig  -lherwig_dummy 
	@ln -fs $(BINDIR)/$@.exe $@.exe
	@echo export LD_LIBRARY_PATH=$(MYLIBSHERWIG):$(PYTHIA6_PATH)/lib:$(CHARYBDIS2_PATH)/lib:$(LD_LIBRARY_PATH) > ldlp.sh

# Clean up: remove executables and outdated files.
.PHONY: clean distclean

clean:
	rm -f $(PROGNAME).exe ldlp.sh $(BINDIR)/data_files data_files

distclean: clean
	rm -f $(BINDIR)/$(PROGNAME).exe
