include ./libtests.mk
include ./config.mk

# Location of directories.
BINDIR=bin

MYEPOSLIBNAME = libcrmc$(SOEXT)
ifeq ($(TESTS_ARCHIVE),1)
 MYEPOSLIBNAME = libcrmc.a
endif

# Create an executable linked to HepMC (if all goes well).
epos_test1: $(EPOS_PATH)/lib/$(MYEPOSLIBNAME)
	 @mkdir -p $(BINDIR)
	 $(CXX) $(CXXFLAGS) -D __WITHOUTBOOST__ \
	 -I$(EPOS_PATH)/include -I$(EPOS_PATH)/../share/sources/src -I$(HEPMC_PATH)/include \
	 $@.cc -o $(BINDIR)/$@.exe \
	 -L$(EPOS_PATH)/lib -L$(HEPMC_PATH)/lib \
	 -lcrmc -lHepMC -lHepMCfio -lgfortran -lgfortranbegin
	 @ln -fs $(BINDIR)/$@.exe $@.exe
	 @echo "export   LD_LIBRARY_PATH=$(EPOS_PATH)/lib:$(HEPMC_PATH)/lib:$(LD_LIBRARY_PATH) ; " > ldlp.sh
	 @echo "export DYLD_LIBRARY_PATH=$(EPOS_PATH)/lib:$(HEPMC_PATH)/lib:$(DYLD_LIBRARY_PATH) ; " >> ldlp.sh

# Clean up: remove executables and outdated files.
.PHONY: clean distclean

clean:
	rm -f $(PROGNAME).exe ldlp.sh crmc.param example_hep.hepmc

distclean: clean
	rm -f $(BINDIR)/$(PROGNAME).exe 

install: $(EPOS_PATH)/lib/$(MYEPOSLIBNAME)

$(EPOS_PATH)/lib/$(MYEPOSLIBNAME):
	cd $(MCGTESTDIR) && \
	cp $(MCGENERATORS)/distribution/epos/epos-$(EPOS_VERSION)-src.tgz . && \
	tar xfz epos-$(EPOS_VERSION)-src.tgz && \
	cd epos/$(EPOS_VERSION) && \
	chmod a+x ./lcg_configure && \
	INSTALL_DIR=$(EPOS_PATH) HEPMC_INSTALL_DIR=$(HEPMC_PATH) ./lcg_configure && \
	mkdir -p $(EPOS_PATH)/../share && \
	ln -sf -T $(MCGTESTDIR)/epos/$(EPOS_VERSION) $(EPOS_PATH)/../share/sources
