include ./libtests.mk
include ./config.mk

# Location of directories.
TMPDIR=tmp
BINDIR=bin

MYPHOJETLIBPATH = $(LIBS_PHOJET_PATH)
MYPHOJETLIBNAME1 = libphojet.so
ifeq ($(TESTS_ARCHIVE),1)
 MYPHOJETLIBPATH = $(LIBS_PHOJET_PATH)/archive
 MYPHOJETLIBNAME1 = libphojet.a
endif

export INSTALL_DIR = $(MYPHOTOSPPLIBPATH)/..
export HEPMC_DIR = $(LIBS_HEPMC_PATH)/..

phojet_test: $(MYPHOJETLIBPATH)/$(MYPHOJETLIBNAME1) fitpar.dat trapfpe.c
	@mkdir -p $(BINDIR)
	$(FC) $(FFLAGS) $(INCLUDE_PHOJET) $(INCLUDE_PYTHIA6) $(INCLUDE_HEPMC) $(PYTHIA6_PATH)/lib/pydata.o \
	-L$(MYPHOJETLIBPATH) -lphojet -lphojet_histodummy -lphojet_pdfdummy \
	-L$(PYTHIA6_PATH)/lib -lpythia6	-lpythia6_dummy -lpythia6_pdfdummy \
	-L$(LIBS_HEPMC_PATH) -lHepMC -lHepMCfio \
	$@.F -o $(BINDIR)/$@.exe \
	$(FLIBS)
	@ln -fs $(BINDIR)/$@.exe ./$@.exe
	@echo export LD_LIBRARY_PATH=$(LD_LIBRARY_PATH):$(MYPHOJETLIBPATH):$(LIBS_PYTHIA6_PATH):$(LIBS_HEPMC_PATH) >> ldlp.sh

# Clean up: remove executables and outdated files.
.PHONY: clean distclean

clean:
	rm -f $(PROGNAME).exe ldlp.sh example_out.dat

distclean: clean
	rm -f $(BINDIR)/$(PROGNAME).exe
