include ./libtests.mk
include ./config.mk

# Location of directories.

TMPDIR=tmp
BINDIR=bin

MYLIBSPOWHEG=$(LIBS_POWHEG_PATH)
MYLIBSPYTHIA=$(LIBS_PYTHIA6_PATH)
MYLIBSLHAPDF=$(LIBS_LHAPDF_PATH)
 MYPBLOCKDATA=
#MYPBLOCKDATA=$(LIBS_PYTHIA6_PATH)/pydata.o 
ifeq ($(TESTS_ARCHIVE),1)
 MYLIBSPOWHEG = $(LIBS_POWHEG_PATH)/archive
 MYLIBSPYTHIA = $(LIBS_PYTHIA6_PATH)/archive
 MYLIBSLHAPDF = $(LIBS_LHAPDF_PATH)/archive
 MYPBLOCKDATA=  
endif

powheg_test: powheg_test.f powheg.input cteq6m
	@mkdir -p $(TMPDIR)
	@mkdir -p $(BINDIR)
	$(FC) $(FFLAGS) $(INCLUDE_POWHEG) $@.f -c -o $(TMPDIR)/$@.o
	$(CXX) $(CXXFLAGS) $(TMPDIR)/$@.o $(MYPBLOCKDATA) -o $(BINDIR)/$@.exe \
	-L$(MYLIBSPYTHIA) -lpythia6 \
	-L$(MYLIBSPOWHEG) -lpowheg \
	-L$(MYLIBSPYTHIA) -lpythia6 -lpythia6_dummy -lpythia6_pdfdummy \
	-L$(LIBTESTS_PATH)/lib/archive -ltests \
	$(FLIBS)
	@ln -fs $(BINDIR)/$@.exe $@.exe
	@rm -f ldlp.sh
	@echo "#!/bin/sh" > ldlp.sh
	@echo export LD_LIBRARY_PATH=$(LIBS_POWHEG_PATH):$(LIBS_PYTHIA6_PATH) >> ldlp.sh

cteq6m: $(POWHEG_PATH)/../share/data/pdfdata/cteq6m
	@ln -fs $(POWHEG_PATH)/../share/data/pdfdata/$@ $@

# Clean up: remove executables and outdated files.
.PHONY: clean distclean

clean:
	rm -f $(PROGNAME).exe ldlp.sh cteq6m pwggrid.* pwgstat.dat pwgubound.dat

distclean: clean
	rm -f $(BINDIR)/$(PROGNAME).exe
	rm *~
