###################################################################################
# MCFM 5.8a and 5.8b are tested
###################################################################################

include ./libtests.mk
include ./config.mk

include $(MCFM_PATH)/config.mk

# Location of directories.
BINDIR=bin

MY_TESTS_LIB_PATH = $(LIBS_LIBTESTS_PATH)/archive
MY_MCFM_LIB_PATH=$(LIBS_MCFM_PATH)
MY_MCFM_LIB_NAME = libMCFM.so
MY_MCFM_EXE_NAME = mcfm

ifeq ($(TESTS_ARCHIVE),1)

 MY_TESTS_LIB_PATH = $(LIBS_LIBTESTS_PATH)/archive
 MY_MCFM_LIB_PATH=$(LIBS_MCFM_PATH)
 MY_MCFM_LIB_NAME = libMCFM.a
 MY_MCFM_EXE_NAME = mcfm_a

endif

LIBDIR=lib
LIBDIRARCH=$(LIBDIR)/archive

PROGNAME=mcfm_test0

mcfm_test0_bin: 
	@mkdir -p $(BINDIR)
	@rm -f PDFsets
	@rm -f Pdfdata
	@ln -fs $(MY_MCFM_LIB_PATH)/../Bin/PDFsets PDFsets
	@ln -fs $(MY_MCFM_LIB_PATH)/../Bin/Pdfdata Pdfdata
	@ln -fs ${MCFM_PATH}/Bin/$(MY_MCFM_EXE_NAME) $(PROGNAME).exe
	@echo export LD_LIBRARY_PATH=$(LIBS_LHAPDF_PATH):$(LIBS_ROOT_PATH):$(MY_MCFM_LIB_PATH):$(MY_TESTS_LIB_PATH):$(LD_LIBRARY_PATH) > ldlp.sh


# Clean up: remove executables and outdated files.
.PHONY: clean distclean mcfm_test0_bin

clean:
	rm -f $(PROGNAME).exe ldlp.sh

distclean: clean
	rm -f $(BINDIR)/$(PROGNAME).exe
