include ./libtests.mk
include ./config.mk

#Location of directories.
TMPDIR=tmp
BINDIR=bin

jimmy_test1 jimmy_test2 :
	@mkdir -p $(BINDIR)
	@mkdir -p $(TMPDIR)
	$(FC) $(FFLAGS) \
	$(INCLUDE_JIMMY) $(INCLUDE_HERWIG) $(INCLUDE_PYTHIA6) \
	$@.F -c -o $(TMPDIR)/$@.o
	$(CXX) $(CXXFLAGS) $(TMPDIR)/$@.o -o $(BINDIR)/$@.exe \
	-L$(LIBS_HERWIG_PATH) -lherwig -lherwig_dummy -lherwig_pdfdummy \
	-L$(LIBS_PYTHIA6_PATH) -lpythia6 -lpythia6_dummy -lpythia6_pdfdummy \
	-L$(LIBS_JIMMY_PATH) -ljimmy \
	-L$(LIBTESTS_PATH)/lib -ltests  -lcernlibgenser $(FLIBS)
	@ln -fs $(BINDIR)/$@.exe $@.exe
	@echo "export LD_LIBRARY_PATH=:$(LIBS_HERWIG_PATH):$(LIBS_JIMMY_PATH):$(LIBS_LIBTESTS_PATH):$(LIBS_PYTHIA6_PATH):$(LD_LIBRARY_PATH)" > ldlp.sh

# Clean up: remove executables and outdated files.
.PHONY: clean distclean

clean:
	rm -f $(PROGNAME).exe ldlp.sh

distclean: clean
	rm -f $(BINDIR)/$(PROGNAME).exe
