include ./libtests.mk
include ./config.mk

# Location of directories.
TMPDIR=tmp
BINDIR=bin

MYPYQUENLIBPATH = $(LIBS_PYQUEN_PATH)
MYPYQUENLIBNAME = libpyquen.so
ifeq ($(TESTS_ARCHIVE),1)
 MYPYQUENLIBPATH = $(LIBS_PYQUEN_PATH)/archive
 MYPYQUENLIBNAME = libpyquen.a
endif

install: $(MYPYQUENLIBPATH)/$(MYPYQUENLIBNAME)
$(MYPYQUENLIBPATH)/$(MYPYQUENLIBNAME) :
	cd $(MCGTESTDIR) && \
	cp $(MCGENERATORS)/distribution/pyquen/pyquen-$(PYQUEN_VERSION)-src.tgz . && \
	tar xfz pyquen-$(PYQUEN_VERSION)-src.tgz && \
	cd pyquen/$(PYQUEN_VERSION) && \
	chmod a+x ./lcg_configure && \
	INSTALL_DIR=$(PYQUEN_PATH) ./lcg_configure && \
	make install

pyquen_test1: $(MYPYQUENLIBPATH)/$(MYPYQUENLIBNAME)
	@mkdir -p $(BINDIR)
	$(FC) $(FFLAGS) -I$(PYQUEN_PATH)/include $@.f -c -o $(TMPDIR)/$@.o
	$(CXX) $(CXXFLAGS) $(TMPDIR)/$@.o -o $(BINDIR)/$@.exe \
	-L$(PYTHIA6_PATH)/lib -lpythia6 \
	-L$(PYQUEN_PATH)/lib -lpyquen \
	-lpythia6_dummy -lpythia6_pdfdummy \
	-L$(LIBTESTS_PATH)/lib/archive -ltests \
	$(FLIBS)
	@ln -fs $(BINDIR)/$@.exe $@.exe
	@echo export LD_LIBRARY_PATH=$(PYTHIA6_PATH)/lib:$(PYQUEN_PATH)/lib:$(LD_LIBRARY_PATH) > ldlp.sh

# Clean up: remove executables and outdated files.
.PHONY: clean distclean

clean:
	rm -f $(PROGNAME).exe ldlp.sh

distclean: clean
	rm -f $(BINDIR)/$(PROGNAME).exe
