include ./libtests.mk
include ./config.mk

# Location of directories.
BINDIR=bin

MY_TESTS_LIB_PATH = $(LIBS_LIBTESTS_PATH)/archive

PROGNAME=starlight_test0

starlight_test0_bin:
	mkdir -p $(BINDIR)
	cp $(SHARE_STARLIGHT_PATH)/sources/config/slight.in.new slight.in
	ln -fs  $(STARLIGHT_PATH)/bin/starlight starlight.exe
	@echo export LD_LIBRARY_PATH=$(LIBS_STARLIGHT_PATH):$(LD_LIBRARY_PATH) > ldlp.sh

starlight_test0:
	$(FC) $(FFLAGS) $(PROGNAME).F -o $(BINDIR)/$@.exe \
	-L$(MY_TESTS_LIB_PATH) -ltests  \
	$(FLIBS)
	@ln -fs $(BINDIR)/$@.exe $@.exe
	@echo export LD_LIBRARY_PATH=$(MY_TESTS_LIB_PATH):$(LD_LIBRARY_PATH) > ldlp.sh


# Clean up: remove executables and outdated files.
.PHONY: clean distclean starlight_test0

clean:
	rm -f $(PROGNAME).exe ldlp.sh

distclean: clean
	rm -f $(BINDIR)/$(PROGNAME).exe
