###################################################################################
# HIJING 1.36.a and 1.36.a.2 are tested
# For HIJING 1.383bs.2 test there is CVS version with the tag: hijing_both_versions
###################################################################################

include ./libtests.mk
include ./config.mk

# Location of directories.
TMPDIR=tmp
BINDIR=bin

MY_TESTS_LIB_PATH = $(LIBS_LIBTESTS_PATH)/archive
MY_HIJING_LIB_PATH=$(LIBS_HIJING_PATH)
MY_HIJING_LIB_NAME = libhijing.so

ifeq ($(TESTS_ARCHIVE),1)
 MY_TESTS_LIB_PATH = $(LIBS_LIBTESTS_PATH)/archive
 MY_HIJING_LIB_PATH=$(LIBS_HIJING_PATH)/archive
 MY_HIJING_LIB_NAME = libhijing.a
 MY_OBJECT_FILES=
endif

PROGNAME_1_36=hijing_test0
MY_OBJECT_FILES_1_36=$(LIBS_HIJING_PATH)/hidata.o  $(LIBS_HIJING_PATH)/ludata_hijing.o $(LIBS_HIJING_PATH)/pydata_hijing.o

hijing_test0: $(MY_HIJING_LIB_PATH)/$(MY_HIJING_LIB_NAME)
	@mkdir -p $(BINDIR)
	$(FC) $(FFLAGS) -I$(INCLUDE_HIJING_PATH) $(PROGNAME_1_36).F -c -o $(TMPDIR)/$@.o
	$(CXX) -O2 $(TMPDIR)/$@.o $(MY_OBJECT_FILES_1_36) \
	-o $(BINDIR)/$@.exe \
	-L$(MY_HIJING_LIB_PATH)  -lhijing -lhijing_dummy -lpythia_hijing -lhijing_dummy   \
	-L$(MY_TESTS_LIB_PATH) -ltests  \
	$(FLIBS)
	@ln -fs $(BINDIR)/$@.exe $@.exe
	@echo export LD_LIBRARY_PATH=$(MY_HIJING_LIB_PATH):$(MY_TESTS_LIB_PATH):$(LD_LIBRARY_PATH) > ldlp.sh


# Clean up: remove executables and outdated files.
.PHONY: clean distclean

clean:
	rm -f $(PROGNAME).exe ldlp.sh

distclean: clean
	rm -f $(BINDIR)/$(PROGNAME).exe
