include ./libtests.mk
include ./config.mk

#Location of directories.
TMPDIR=tmp
BINDIR=bin

pomwig_test1 :
	@mkdir -p $(BINDIR)
	@mkdir -p $(TMPDIR)
	$(FC) -fno-second-underscore -fno-automatic $(FFLAGS) \
	$(INCLUDE_HERWIG) \
	$@.F -c -o $(TMPDIR)/$@.o
	$(FC)  -fno-second-underscore -fno-automatic $(FFLAGS) \
         $(HERWIG_PATH)/lib/hwudat.o \
         $(TMPDIR)/$@.o -o $(BINDIR)/$@.exe \
         -L$(LIBS_POMWIG_PATH)  -lpomwig     \
        -L$(LIBS_HERWIG_PATH) -lherwig -lherwig_dummy -lherwig_pdfdummy 
	@ln -fs $(BINDIR)/$@.exe $@.exe
	@echo export \
	LD_LIBRARY_PATH=:$(LIBS_HERWIG_PATH):$(LIBS_POMWIG_PATH):$(LD_LIBRARY_PATH) > ldlp.sh 

# Clean up: remove executables and outdated files.
.PHONY: clean distclean

clean:
	rm -f $(PROGNAME).exe ldlp.sh

distclean: clean
	rm -f $(BINDIR)/$(PROGNAME).exe
