include ./libtests.mk
include ./config.mk

# Location of directories.
TMPDIR=tmp
BINDIR=bin

MY_TESTS_LIB_PATH = $(LIBS_LIBTESTS_PATH)/archive

ifeq ($(TESTS_ARCHIVE),1)
 MY_TESTS_LIB_PATH = $(LIBS_LIBTESTS_PATH)/archive
endif

PROGNAME=mcfm_test0

mcfm_test0: 
	@mkdir -p $(BINDIR)
	$(FC) $(FFLAGS) $(PROGNAME).F -c -o $(TMPDIR)/$@.o
	$(CXX) -O2 $(TMPDIR)/$@.o  \
	-o $(BINDIR)/$@.exe \
	-L$(MY_TESTS_LIB_PATH) -ltests  \
	$(FLIBS)
	@ln -fs $(BINDIR)/$@.exe $@.exe
	@echo export LD_LIBRARY_PATH=$(MY_TESTS_LIB_PATH):$(LD_LIBRARY_PATH) > ldlp.sh


# Clean up: remove executables and outdated files.
.PHONY: clean distclean mcfm_test0x

clean:
	rm -f $(PROGNAME).exe ldlp.sh

distclean: clean
	rm -f $(BINDIR)/$(PROGNAME).exe
