###################################################################################
# HEJ 1.2 is tested
###################################################################################

include ./libtests.mk
include ./config.mk

# Location of directories.
TMPDIR=tmp
BINDIR=bin

MY_TESTS_LIB_PATH = $(LIBS_LIBTESTS_PATH)/archive
MY_ROOT_PATH = /afs/cern.ch/sw/lcg/app/releases/ROOT/5.22.00d/$(PLATFORM)/root/lib
MY_CLHEP_PATH = /afs/cern.ch/sw/lcg/external/clhep/2.0.4.7/$(PLATFORM)/lib
MY_GSL_PATH = /afs/cern.ch/sw/lcg/external/GSL/1.10/$(PLATFORM)/lib
MY_LHAPDF_PATH = /afs/cern.ch/sw/lcg/external/MCGenerators/lhapdf/5.8.4/$(PLATFORM)/lib
MY_FASTJET_PATH = /afs/cern.ch/sw/lcg/external/fastjet/2.4.2p5/$(PLATFORM)/lib

MY_HEJ_LIB_PATH=$(LIBS_MCFM_PATH)

PROGNAME=hej_test0

hej_test0_bin: 
	@mkdir -p $(BINDIR)
	@cp /afs/cern.ch/sw/lcg/external/MCGenerators/hej/1.2/share/sources/input_jets_vanilla .
	@ln -fs /afs/cern.ch/sw/lcg/external/MCGenerators/hej/1.2/share/Grids
	@ln -fs  ${HEJ_PATH}/bin/JetGen JetGen
	@echo export LD_LIBRARY_PATH=$(MY_GSL_PATH):$(MY_CLHEP_PATH):$(MY_LHAPDF_PATH):$(MY_FASTJET_PATH):$(MY_ROOT_PATH):$(MY_HEJ_LIB_PATH):$(LD_LIBRARY_PATH) > ldlp.sh

hej_test0: 
	@mkdir -p $(BINDIR)
	$(FC) $(FFLAGS) $(PROGNAME).F -c -o $(TMPDIR)/$@.o
	$(CXX) -O2 $(TMPDIR)/$@.o  \
	-o $(BINDIR)/$@.exe \
	-L$(MY_TESTS_LIB_PATH) -ltests  \
	$(FLIBS)
	@ln -fs $(BINDIR)/$@.exe $@.exe
	@echo export LD_LIBRARY_PATH=$(MY_TESTS_LIB_PATH):$(LD_LIBRARY_PATH) > ldlp.sh



# Clean up: remove executables and outdated files.
.PHONY: clean distclean hej_test0

clean:
	rm -f $(PROGNAME).exe ldlp.sh

distclean: clean
	rm -f $(BINDIR)/$(PROGNAME).exe
