include ./libtests.mk
include ./config.mk

# Location of directories.
BINDIR=bin

MYPYTHIA8LIBPATH = $(PYTHIA8_PATH)/lib
MYPYTHIA8LIBNAME1 = libpythia8$(SOEXT)
MYPYTHIA8LIBNAME2 = libhepmcinterface$(SOEXT)
ifeq ($(TESTS_ARCHIVE),1)
 MYPYTHIA8LIBPATH = $(PYTHIA8_PATH)/lib/archive
 MYPYTHIA8LIBNAME1 = libpythia8.a
 MYPYTHIA8LIBNAME2 = libhepmcinterface.a
endif

MYTESTSLIBPATH = $(LIBS_LIBTESTS_PATH)/archive

# Create an executable linked to HepMC and CLHEP (if all goes well).
pythia8_test1: $(MYPYTHIA8LIBPATH)/$(MYPYTHIA8LIBNAME1) $(MYPYTHIA8LIBPATH)/$(MYPYTHIA8LIBNAME2)
	 @mkdir -p $(BINDIR)
	 $(CXX) $@.cc -o $(BINDIR)/$@.exe $(CXXFLAGS) \
	 $(INCLUDE_LIBTESTS) -I$(PYTHIA8_PATH)/include \
	 -I$(HEPMC_PATH)/include -I$(CLHEP_PATH)/include \
	 -L$(MYPYTHIA8LIBPATH) -lpythia8 -lhepmcinterface -llhapdfdummy \
	 -L$(MYTESTSLIBPATH) -lanalyserhepmc \
	 -L$(HEPMC_PATH)/lib -lHepMC \
	 $(LIBS_CLHEP) 
	 @ln -fs $(BINDIR)/$@.exe $@.exe
	 @echo "export   LD_LIBRARY_PATH=$(MYPYTHIA8LIBPATH):$(HEPMC_PATH)/lib:$(CLHEP_PATH)/lib:$(LD_LIBRARY_PATH) ; " > ldlp.sh
	 @echo "export DYLD_LIBRARY_PATH=$(MYPYTHIA8LIBPATH):$(HEPMC_PATH)/lib:$(CLHEP_PATH)/lib:$(DYLD_LIBRARY_PATH) ; " >> ldlp.sh

pythia8_test2: $(MYPYTHIA8LIBPATH)/$(MYPYTHIA8LIBNAME1) $(MYPYTHIA8LIBPATH)/$(MYPYTHIA8LIBNAME2)
	 @mkdir -p $(BINDIR)
	 $(CXX) $(CXXFLAGS) \
	 $(INCLUDE_LIBTESTS) -I$(PYTHIA8_PATH)/include \
	 -I$(HEPMC_PATH)/include -I$(CLHEP_PATH)/include \
	 $@.cc -o $(BINDIR)/$@.exe \
	 -L$(MYPYTHIA8LIBPATH) -lpythia8 -lhepmcinterface -llhapdfdummy \
	 -L$(LIBS_PYTHIA6_PATH)/archive -lpythia6 -lpythia6_dummy -lpythia6_pdfdummy \
	 -L$(MYTESTSLIBPATH) -lanalyserhepmc \
	 -L$(HEPMC_PATH)/lib -lHepMC \
	 -L$(CLHEP_PATH)/lib -lCLHEP \
	 $(FLIBS)
	 @ln -fs $(BINDIR)/$@.exe $@.exe
	 @echo "export   LD_LIBRARY_PATH=$(MYPYTHIA8LIBPATH):$(HEPMC_PATH)/lib:$(CLHEP_PATH)/lib:$(LD_LIBRARY_PATH) ;"  > ldlp.sh
	 @echo "export DYLD_LIBRARY_PATH=$(MYPYTHIA8LIBPATH):$(HEPMC_PATH)/lib:$(CLHEP_PATH)/lib:$(DYLD_LIBRARY_PATH) ;" >> ldlp.sh

pythia8_test3: $(MYPYTHIA8LIBPATH)/$(MYPYTHIA8LIBNAME1) $(MYPYTHIA8LIBPATH)/$(MYPYTHIA8LIBNAME2)
	 @mkdir -p $(BINDIR)
	 $(CXX) $(CXXFLAGS) \
	 $(INCLUDE_LIBTESTS) -I$(PYTHIA8_PATH)/include \
	 -I$(HEPMC_PATH)/include -I$(CLHEP_PATH)/include \
	 $@.cc -o $(BINDIR)/$@.exe \
	 -L$(MYPYTHIA8LIBPATH) -lpythia8 -lhepmcinterface -llhapdfdummy \
	 -L$(MYTESTSLIBPATH) -lanalyserhepmc \
	 -L$(HEPMC_PATH)/lib -lHepMC \
	 -L$(CLHEP_PATH)/lib -lCLHEP \
	 $(FLIBS)
	 @ln -fs $(BINDIR)/$@.exe $@.exe
	 @echo "export   LD_LIBRARY_PATH=$(MYPYTHIA8LIBPATH):$(HEPMC_PATH)/lib:$(CLHEP_PATH)/lib:$(LD_LIBRARY_PATH) ;"  > ldlp.sh
	 @echo "export DYLD_LIBRARY_PATH=$(MYPYTHIA8LIBPATH):$(HEPMC_PATH)/lib:$(CLHEP_PATH)/lib:$(DYLD_LIBRARY_PATH) ;" >> ldlp.sh

pythia8_test4: $(MYPYTHIA8LIBPATH)/$(MYPYTHIA8LIBNAME1) $(MYPYTHIA8LIBPATH)/$(MYPYTHIA8LIBNAME2)
	@mkdir -p $(BINDIR)
	$(CXX) $(CXXFLAGS) \
	-I$(PYTHIA8_PATH)/include \
	-I$(HEPMC_PATH)/include \
	$@.cc -o $(BINDIR)/$@.exe \
	-L$(MYPYTHIA8LIBPATH) -lpythia8 -lhepmcinterface -llhapdfdummy \
	-L$(HEPMC_PATH)/lib -lHepMC \
	$(FLIBS)
	@ln -fs $(BINDIR)/$@.exe $@.exe
	@echo "export   LD_LIBRARY_PATH=$(MYPYTHIA8LIBPATH):$(HEPMC_PATH)/lib:$(LD_LIBRARY_PATH) ;"  > ldlp.sh
	@echo "export DYLD_LIBRARY_PATH=$(MYPYTHIA8LIBPATH):$(HEPMC_PATH)/lib:$(DYLD_LIBRARY_PATH) ;" >> ldlp.sh

# Clean up: remove executables and outdated files.
.PHONY: clean distclean

ifeq ($(PROGNAME),pythia8_test2)
 clean:
	rm -f $(PROGNAME).exe ldlp.sh Zg.lhe
else
 clean:
	rm -f $(PROGNAME).exe ldlp.sh
endif

distclean: clean
	rm -f $(BINDIR)/$(PROGNAME).exe 

install: $(MYPYTHIA8LIBPATH)/$(MYPYTHIA8LIBNAME1)

$(MYPYTHIA8LIBPATH)/$(MYPYTHIA8LIBNAME1):
	cd $(MCGTESTDIR) && \
	cp $(MCGENERATORS)/distribution/pythia8/pythia8-$(PYTHIA8_VERSION)-src.tgz . && \
	tar xfz pythia8-$(PYTHIA8_VERSION)-src.tgz && \
	cd pythia8/$(PYTHIA8_VERSION) && \
	./configure --enable-shared --prefix=${PYTHIA8_PATH} --with-hepmc=${HEPMC_PATH} && \
	make install
