
#find_path(PHOTOSPP_INCLUDE_DIR Photos.h
#          HINTS $ENV{PHOTOSPP_ROOT_DIR}/include/Photos/ ${PHOTOSPP_ROOT_DIR}/include/Photos/)

find_library(PHOTOSPP_LIBRARY NAMES PhotosCxxInterface
             HINTS $ENV{PHOTOSPP_ROOT_DIR}/lib ${PHOTOSPP_ROOT_DIR}/lib)

set(PHOTOSPP_INCLUDE_DIR ${PHOTOSPP_ROOT_DIR}/include)
set(PHOTOSPP_INCLUDE_DIRS ${PHOTOSPP_INCLUDE_DIR})
set(PHOTOSPP_LIBRARIES ${PHOTOSPP_LIBRARY})

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(Photos++ DEFAULT_MSG PHOTOSPP_INCLUDE_DIR PHOTOSPP_LIBRARY)

mark_as_advanced(PHOTOSPP_FOUND PHOTOSPP_INCLUDE_DIR PHOTOSPP_LIBRARY)