#find_path(THEPEG_INCLUDE_DIR ThePEG/ 
#          HINTS $ENV{THEPEG_ROOT_DIR}/include ${THEPEG_ROOT_DIR}/include)

find_library(THEPEG_LIBRARIES NAMES ThePEG
             HINTS $ENV{THEPEG_ROOT_DIR}/lib/ThePEG/ ${THEPEG_ROOT_DIR}/lib/ThePEG/)

set(THEPEG_INCLUDE_DIR ${THEPEG_ROOT_DIR}/include)

set(THEPEG_INCLUDE_DIRS ${THEPEG_INCLUDE_DIR})

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(Thepeg DEFAULT_MSG THEPEG_INCLUDE_DIR THEPEG_LIBRARIES)

mark_as_advanced(THEPEG_FOUND THEPEG_INCLUDE_DIR THEPEG_LIBRARIES)
