find_path(EVTGEN_INCLUDE_DIR EvtGen/EvtGen.hh
          HINTS $ENV{EVTGEN_ROOT_DIR}/include/ ${EVTGEN_ROOT_DIR}/include/)

find_library(EVTGEN_LIBRARY NAMES EvtGen
             HINTS $ENV{EVTGEN_ROOT_DIR}/lib ${EVTGEN_ROOT_DIR}/lib)

set(EVTGEN_INCLUDE_DIR ${EVTGEN_ROOT_DIR}/include)
set(EVTGEN_INCLUDE_DIRS ${EVTGEN_INCLUDE_DIR})
set(EVTGEN_LIBRARIES ${EVTGEN_LIBRARY})

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(Evtgen DEFAULT_MSG EVTGEN_INCLUDE_DIR EVTGEN_LIBRARY)

mark_as_advanced(EVTGEN_FOUND EVTGEN_INCLUDE_DIR EVTGEN_LIBRARY)